[package]
name = "ftd2xx-sys"
version = "0.1.0"
authors = ["Gregory Mitrano <gregory.mitrano@gmail.com>"]
edition = "2018"
links = "ftd2xx"

[features]
gen-bindings = ["bindgen"]

[build-dependencies]
bindgen = { version = "0.54.0", optional = true }